apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      serviceAccountName: java-app-sa
      containers:
        - name: java-app
          image: your-dockerhub-username/java-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-east-2" # or your region
